version: '2'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      DB_PORT: 3306
      DB_HOST: database
    links:
      - database:database


  # The Web Server
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8080:80

  database:
    restart: always
    image: mariadb:10.3.13
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3308:3306"
    volumes:
      - ./dbdata/database/:/var/lib/mariadb
      - ./db-init-scripts/:/docker-entrypoint-initdb.d
