version: '3'

networks:
  laravel:

volumes:
  data:
    driver: "local"

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgres
    networks:
      - laravel

  postgres:
    container_name: db
    build: ./docker/postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: stratosphere
      POSTGRES_USER: stratosphere
      POSTGRES_PASSWORD: 12345
      #SERVICE_TAGS: dev
      SERVICE_NAME: postgres
    volumes:
       - data:/var/lib/postgresql/data
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: php
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - laravel

  npm:
    image: node:13.7
    container_name: npm
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']

  artisan:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: artisan
    volumes:
      - ./:/var/www/html
    depends_on:
      - postgres
    working_dir: /var/www/html
    entrypoint: ['/var/www/html/artisan']
    networks:
      - laravel
